# Generated by Django 4.0.5 on 2024-07-02 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupclasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('classteacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teachers')),
            ],
            options={
                'verbose_name': 'Group class',
                'verbose_name_plural': 'Group classes',
            },
        ),
        migrations.CreateModel(
            name='Groupsubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Group subject',
                'verbose_name_plural': 'Group subjects',
            },
        ),
        migrations.CreateModel(
            name='SchoolGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('lessonduration', models.PositiveIntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Groupsubjectteachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nooflessonsperweek', models.PositiveIntegerField()),
                ('groupsubjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groupsubjects')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teachers')),
                ('theclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groupclasses')),
            ],
            options={
                'verbose_name': 'Group subject teacher',
                'verbose_name_plural': 'Group subject teachers',
            },
        ),
        migrations.AddField(
            model_name='groupsubjects',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.schoolgroups'),
        ),
        migrations.AddField(
            model_name='groupsubjects',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subjects'),
        ),
        migrations.CreateModel(
            name='GroupSpecifiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('groupsubjectteachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groupsubjectteachers')),
            ],
            options={
                'verbose_name': 'Group specificationr',
                'verbose_name_plural': 'Group specificationrs',
            },
        ),
        migrations.CreateModel(
            name='Grouproutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.schoolgroups')),
            ],
            options={
                'verbose_name': 'Group routine',
                'verbose_name_plural': 'Group routines',
            },
        ),
        migrations.AddField(
            model_name='groupclasses',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.schoolgroups'),
        ),
        migrations.AddField(
            model_name='groupclasses',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.streams'),
        ),
        migrations.CreateModel(
            name='Groupbreaks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakname', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.schoolgroups')),
            ],
            options={
                'verbose_name': 'Group break',
                'verbose_name_plural': 'Group breaks',
            },
        ),
    ]
